// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/GatingSetLoader.h"
#include <Rcpp.h>

using namespace Rcpp;

// loadGatingSet
XPtr<GatingSet> loadGatingSet(string fileName, unsigned short format);
RcppExport SEXP GatingSetLoader_loadGatingSet(SEXP fileNameSEXP, SEXP formatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< unsigned short >::type format(formatSEXP);
    __result = Rcpp::wrap(loadGatingSet(fileName, format));
    return __result;
END_RCPP
}
