// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/GatingSetLoader.h"
#include <Rcpp.h>

using namespace Rcpp;

// saveGatingSet
void saveGatingSet(XPtr<GatingSet> gs, string fileName, unsigned short format, bool isPB);
RcppExport SEXP GatingSetLoader_saveGatingSet(SEXP gsSEXP, SEXP fileNameSEXP, SEXP formatSEXP, SEXP isPBSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<GatingSet> >::type gs(gsSEXP);
    Rcpp::traits::input_parameter< string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< unsigned short >::type format(formatSEXP);
    Rcpp::traits::input_parameter< bool >::type isPB(isPBSEXP);
    saveGatingSet(gs, fileName, format, isPB);
    return R_NilValue;
END_RCPP
}
// loadGatingSet
XPtr<GatingSet> loadGatingSet(string fileName, unsigned short format, bool isPB);
RcppExport SEXP GatingSetLoader_loadGatingSet(SEXP fileNameSEXP, SEXP formatSEXP, SEXP isPBSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< unsigned short >::type format(formatSEXP);
    Rcpp::traits::input_parameter< bool >::type isPB(isPBSEXP);
    __result = Rcpp::wrap(loadGatingSet(fileName, format, isPB));
    return __result;
END_RCPP
}
