# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cpp_loadGatingSet <- function(fileName, format) {
    .Call('GatingSetLoader_loadGatingSet', PACKAGE = 'GatingSetLoader', fileName, format)
}

